version: "3.8"

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: app-api
    env_file:
      - ./Api/.env.prod
    expose:
      - "8800"
    restart: unless-stopped
    networks:
      - app-net

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    container_name: app-socket
    env_file:
      - ./socket/.env.prod
    expose:
      - "4000"
    restart: unless-stopped
    networks:
      - app-net

  web:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: app-web
    depends_on:
      - api
      - socket
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
